### ISSUE TITLE
Error in Output 

### ISSUE THREAD

**Issue by geodeepak** [ydluo/qdyn#41] opened 2020-03-15 12:45 UTC
The p.ot giving nan value for every parameter.
Python as well as Matlab Wrapper not giving output with p.ot.
Please help.

**Comment by martijnende** [comment] 2020-03-15 13:05
Could you provide details of how to reproduce the problem?

**Comment by geodeepak** [comment] 2020-03-15 13:28
As I extracted the Fort.18 file in excel every value is at its position. But while calling the output file in any one of these wrapper I am not getting any plot. over jupyter as well as in matlab.

**Comment by geodeepak** [comment] 2020-03-15 13:35
> Could you provide details of how to reproduce the problem?

I'm just running your example provided in the manual using Jupyter Notebook.

**Comment by martijnende** [comment] 2020-03-15 13:44
> > Could you provide details of how to reproduce the problem?
> 
> I'm just running your example provided in the manual using Jupyter Notebook.

Which example did you try?

**Comment by geodeepak** [comment] 2020-03-15 13:52
> > > Could you provide details of how to reproduce the problem?
> > 
> > 
> > I'm just running your example provided in the manual using Jupyter Notebook.
> 
> Which example did you try?

Spring block,  RSF, and Singel Asperity

**Comment by martijnende** [comment] 2020-03-15 14:12
I've just run the example notebooks, and I cannot reproduce the problem. Are you running the latest version? (`2e6646df3b0fbbe4e41dac1b3450b2dbc80c8de4`)

**Comment by geodeepak** [comment] 2020-03-16 12:01
> I've just run the example notebooks, and I cannot reproduce the problem. Are you running the latest version? (`2e6646df3b0fbbe4e41dac1b3450b2dbc80c8de4`)

Yes

**Comment by martijnende** [comment] 2020-03-16 12:12
There have been a few undocumented releases since `2.2.2`, so make 100% sure you have compiled the latest commit (`git pull origin master` and `make clean && make` in your `src` directory). 

You can attach files (screenshots) by dragging and dropping into the comment box.

**Comment by geodeepak** [comment] 2020-03-16 12:58
@
![2020-03-16 (1)](https://user-images.githubusercontent.com/59430963/76760595-ef4f9b00-67b3-11ea-9a03-017bb97b0377.png)

-

**Comment by geodeepak** [comment] 2020-03-16 13:01
![2020-03-16 (2)](https://user-images.githubusercontent.com/59430963/76760779-448bac80-67b4-11ea-9223-8a3882c79a07.png)

**Comment by geodeepak** [comment] 2020-03-16 13:01
![2020-03-16 (3)](https://user-images.githubusercontent.com/59430963/76760834-62f1a800-67b4-11ea-955a-ed040b64ca8a.png)

**Comment by geodeepak** [comment] 2020-03-16 13:12
This is the issue that I am getting.
there is no problem with p.ox file you can see this in the 2nd screenshot. But p.ot is not giving values.
As I opened the Fort file all the values are at its place.

**Comment by martijnende** [comment] 2020-03-16 17:12
Could you revert to commit `d9afd684dd5a5269e1f4bfea831faddcab48b46d` and check if the problem persists: `git checkout d9afd68 && make clean && make` in your `src` directory. Make sure to fully reload the notebooks.

**Comment by geodeepak** [comment] 2020-03-17 05:22
> git checkout d9afd68

Did it but still getting the issue....

**Comment by martijnende** [comment] 2020-03-17 08:07
From your screenshots it seems that `fort.18` is fine, so that the problem must be in the file reader module. What is your version of Pandas?

**Comment by geodeepak** [comment] 2020-03-17 10:50
> From your screenshots it seems that `fort.18` is fine, so that the problem must be in the file reader module. What is your version of Pandas?

Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :

**Comment by martijnende** [comment] 2020-03-17 12:22
And your Pandas version? `import pandas, print(pandas.__version__)`

**Comment by geodeepak** [comment] 2020-03-17 15:21
> And your Pandas version? `import pandas, print(pandas.__version__)`

pandas version 0.25.1

**Comment by martijnende** [comment] 2020-03-17 16:12
Hmm, that shouldn't be a problem then. Could you attach your `fort.18` to this thread (drag and drop)?

**Comment by geodeepak** [comment] 2020-03-18 16:43
[fort.txt](https://github.com/ydluo/qdyn/files/4350183/fort.txt)

**Comment by geodeepak** [comment] 2020-03-22 10:55
> Hmm, that shouldn't be a problem then. Could you attach your `fort.18` to this thread (drag and drop)?

I attached the fort.txt after changing the  extension.

**Comment by martijnende** [comment] 2020-03-22 19:31
I'll see if I can have a closer look tomorrow

**Comment by martijnende** [comment] 2020-03-27 13:20
I've finally had a chance to look at your `fort.18` file. What I noticed, is that yours is comma delimited, while all output should be delimited by white spaces. Any idea why your output is comma delimited?

**Comment by geodeepak** [comment] 2020-03-27 14:13
> I've finally had a chance to look at your `fort.18` file. What I noticed, is that yours is comma delimited, while all output should be delimited by white spaces. Any idea why your output is comma delimited?

How would I know I haven't changed anything in the code. I just tried to run the examples only.

**Comment by martijnende** [comment] 2020-03-27 14:32
A quick fix for you would be to go to `src/pyqdyn.py` and modify line `546` replacing `delim_whitespace=True` with `delimiter=","`. Could you check if that fixes the issue?

**Comment by geodeepak** [comment] 2020-03-27 15:21
Thank you it worked,
Is it possible to use 3D simulation using python.

**Comment by martijnende** [comment] 2020-03-27 15:32
> Thank you it worked,

Good to hear that (temporarily) fixes the issue. I'll see if I can figure out why you get comma separated output in the first place.

> Is it possible to use 3D simulation using python.

Yes, though 3D simulations have not been tested using the Python wrapper, so you might run into some issues along the way.

**Comment by geodeepak** [comment] 2020-03-27 15:43
> > Thank you it worked,
> 
> Good to hear that (temporarily) fixes the issue. I'll see if I can figure out why you get comma separated output in the first place.
> 
> > Is it possible to use 3D simulation using python.
> 
> Yes, though 3D simulations have not been tested using the Python wrapper, so you might run into some issues along the way.

Ok, Thank You. I will try, if I will encounter any issues then I will contact you.

**Comment by jpampuero** [comment] 2020-03-27 21:08
The comma is not a bug but a feature when OCTAVE_OUTPUT is enabled (line 279 of src/output.f90).
You are not using Octave, thus you should set OCTAVE_OUTPUT = .false. in constants.f90, and then recompile the qdyn code (run make).

**Comment by martijnende** [comment] 2020-03-28 08:03
That is a good point, I didn't think of that. When you set `OCTAVE_OUTPUT = .false.`, then don't forget to revert back to `delim_whitespace=True` in `pyqdyn.py:546`.

Since apparently this behaviour is not caused by a bug in the code, I will now close the issue.

**Closed by martijnende** 2020-03-28 08:03 UTC

**Comment by geodeepak** [comment] 2020-03-28 08:43
> That is a good point, I didn't think of that. When you set `OCTAVE_OUTPUT = .false.`, then don't forget to revert back to `delim_whitespace=True` in `pyqdyn.py:546`.
> 
> Since apparently this behaviour is not caused by a bug in the code, I will now close the issue.

well as I checked Constants.f90  the octave output is false.

**Comment by geodeepak** [comment] 2020-03-28 08:44
![Screenshot from 2020-02-28 18-11-36](https://user-images.githubusercontent.com/59430963/77819118-6e22cd00-70fe-11ea-8417-8014ab84b7e1.png)

**Comment by geodeepak** [comment] 2020-03-28 08:49
![Screenshot from 2020-03-28 14-19-03](https://user-images.githubusercontent.com/59430963/77819224-26507580-70ff-11ea-97f7-ec63bb5c4ed0.png)
